services:
  - type: web
    name: guana-go-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        value: appiReH55Qhrbv4Lk
      - key: AIRTABLE_TABLE_NAME
        value: Directorio_Mapa
      - key: VITE_MAPBOX_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
